### ISSUE TITLE
Uncaught TypeError: url.parse is not a function

### ISSUE THREAD

**Issue by robtry** [willfrew/node-random-org#17]
I am trying to import it in an React Application but it throws the error
`Uncaught TypeError: url.parse is not a function RandomOrg.js:11`

vite":·"^2.8.0
node: v16.13.2
react: 17.0.2

**Comment by robtry** [comment]
Update: Change from vite to create react app and the error change to
`Uncaught Error: Cannot find module url`
So i fix it `yarn add url`
Now the error is `Uncaught Error: Cannot find module 'https'`

Also the same for vite

**Comment by willfrew** [comment]
Hi @robtry, sorry for the late response!

This package is specifically designed for nodejs (i.e. running on the backend) rather than running in the browser.

You could try to pull in polyfills for the builtin node dependencies like `https` / `url` etc to get it to work (although it's worth checking whether that'd be appropriate for a production application, if that's what you're doing).

In webpack I'd use the [`resolve.fallback`](https://webpack.js.org/configuration/resolve/#resolvefallback) config to polyfill those packages. I've not used vite before but it looks like you might be able to achieve the same thing with their [`resolve.alias`](https://vitejs.dev/config/#resolve-alias) config.

If I'm not too late with my response (apologies again!), give that a try and let me know if any other issues.
